### ISSUE TITLE
How to backup and restore DTR

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1722]
DTR 2.2 has backup and restore [docs here](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/backups-and-disaster-recovery/), but a bunch of users are having problems when following these instructions.

- [x] Explain when backup and restores should be used. Check #1720
- [x] Review that the current docs work on DTR 2.2
- [x] Make it clear what the DTR backup saves and what doesn't. Check #1704 
- [x] How do I test if a backup succeeded
- [ ] How do I backup/restore images when using an external storage
- [x] When restoring you must your the same docker/dtr tag that created the backup. Check #1685

**Comment by vikstrous** [comment]
dibs
