### ISSUE TITLE
How to backup and restore UCP

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1724]
UCP 2.1 has backup and restore [docs here](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/backups-and-disaster-recovery/), but a bunch of users are having problems when following these instructions

- [x] Explain when backup and restore should be used, specially when I already have HA. Check #671 and #1083
- [x] Explain how many backups you need to create. Check #1651
- [x] Review that the current docs work on UCP 2.1
- [x] How do I test if a backup succeeded
- [x] Make it clear what UCP backup saves and what doesn't
- [x] When restoring you must your the same docker/dtr tag that created the backup. Check #1685
