### ISSUE TITLE
EPIC: Improve storage/graph driver docs

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#2770]
This is a list of issues around storage drivers that are causing some confusion, specially with users installing Docker EE.

* [ ] Make clear the distinction between storage and volume drivers #1126 
* [ ] Make clear that the aufs driver is stable and supported #2733
* [ ] Document the support matrix for Docker/OS/Drivers #2769
* [ ] In RHEL you should use devicemapper for production, but it required manual configurations so we need to document what those configs are

**Comment by LongLiveCHIEF** [comment]
there's a few other mistakes in the devicemapper setup docs that I'm attempting to clean up also. Related to #3032 - Consistent device usage in devicemapper examples

**Comment by mstanleyjones** [comment]
These docs had significant rewrites for Docker 17.06 CE. I believe all are addressed. See #3386.
